name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: LegionT5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy
      run: |
        if [ ! -f .env ]; then
          echo "Creating .env file..."
          echo "OPEN_WEATHER_KEY=${{ secrets.OPEN_WEATHER_API_KEY }}" > .env
          echo "GENERATE_API_URL=${{ secrets.GENERATE_API_URL }}" >> .env
          echo "GENERATE_NOTE_PROMPT=${{ secrets.GENERATE_NOTE_PROMPT }}" >> .env
          echo "GENERATE_API_KEY=${{ secrets.GENERATE_API_KEY }}" >> .env
          echo "WHATBEATS_API_URL=${{ secrets.WHATBEATS_API_URL }}" >> .env
          echo "GENERATE_IMAGE_API_URL=${{ secrets.GENERATE_IMAGE_API_URL }}" >> .env
        fi
        
    - name: Stop and Remove Existing Container
      run: |
        docker-compose down || true  # Stops and removes existing containers, but doesn’t fail if they don't exist

    - name: Remove Unused Images
      run: |
        docker image prune -af  # Cleans up old images to save space

    - name: Deploy Application
      run: |
        docker-compose up -d --build
