name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master  # or the branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH to Raspberry Pi and Redeploy
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 2222
        script: |
          cd ~/miscellaneous_API || exit 1
          git pull || exit 1
          rm .env || true
          # Check if .env file exists, if not, create it with default content
          if [ ! -f .env ]; then
            echo "Creating .env file..."
            echo "OPEN_WEATHER_KEY=${{ secrets.OPEN_WEATHER_API_KEY }}" > .env
            echo "GENERATE_API_URL=${{ secrets.GENERATE_API_URL }}" >> .env
            echo "GENERATE_NOTE_PROMPT=${{ secrets.GENERATE_NOTE_PROMPT }}" >> .env
            echo "GENERATE_API_KEY=${{ secrets.GENERATE_API_KEY }}" >> .env
          fi
          
          docker build -t my_fast_api . || exit 1
          docker stop myfastapi || true
          docker rm myfastapi || true
          docker run -d --network host --restart always --name myfastapi my_fast_api || exit 1

